<?php

namespace easpaylib;

/**
 * Possible Errors (code on message object)
 */
class Error
{
    const OPERATION_INVALID = "OPERATION_INVALID";
    const INVALID_AMOUNT_FORMAT = "INVALID_AMOUNT_FORMAT";
    const MISSING_MANDATORY_FIELD = "MISSING_MANDATORY_FIELD";
    const SUBSCRIPTION_ALREADY_CANCELED = "SUBSCRIPTION_ALREADY_CANCELED";
    const RENEWAL_TO_EARLY = "RENEWAL_TO_EARLY";
    const TRANSACTION_ALREADY_REJECTED = "TRANSACTION_ALREADY_REJECTED";
    const TRANSACTION_ALREADY_COMMITTED = "TRANSACTION_ALREADY_COMMITTED";
    const TRANSACTION_NOT_COMMITTED = "TRANSACTION_NOT_COMMITTED";
    const CE_NOT_AUTHORIZED = "CE_NOT_AUTHORIZED";
    const CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE = "CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE";
    const CE_NOT_AUTHORIZED_BARRING_STATE_REACHED = "CE_NOT_AUTHORIZED_BARRING_STATE_REACHED";
    const CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING";
    const CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO";
    const CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED = "CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED";
    const CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT = "CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT";
    const CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED = "CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED";
    const CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED";
    const CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED";
    const CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT = "CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT";
}
