package com.swisscom.easypay.clientlibrary;

/**
 * Possible Errors (code on message object)
 */
public class Error {
    private Error() {} // prevent instantiation

    public final static String OPERATION_INVALID ="OPERATION_INVALID";
    public final static String INVALID_AMOUNT_FORMAT="INVALID_AMOUNT_FORMAT";
    public final static String MISSING_MANDATORY_FIELD="MISSING_MANDATORY_FIELD";
    public final static String SUBSCRIPTION_ALREADY_CANCELED="SUBSCRIPTION_ALREADY_CANCELED";
    public final static String RENEWAL_TO_EARLY="RENEWAL_TO_EARLY";
    public final static String TRANSACTION_ALREADY_REJECTED="TRANSACTION_ALREADY_REJECTED";
    public final static String TRANSACTION_ALREADY_COMMITTED="TRANSACTION_ALREADY_COMMITTED";
    public final static String TRANSACTION_NOT_COMMITTED="TRANSACTION_NOT_COMMITTED";
    public final static String CE_NOT_AUTHORIZED="CE_NOT_AUTHORIZED";
    public final static String CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE="CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE";
    public final static String CE_NOT_AUTHORIZED_BARRING_STATE_REACHED="CE_NOT_AUTHORIZED_BARRING_STATE_REACHED";
    public final static String CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING="CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING";
    public final static String CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO="CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED = "CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT="CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED="CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED="CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED="CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED";
    public final static String CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT="CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT";
}
