"use strict";
var easypay;
(function (easypay) {
    var Error;
    (function (Error) {
        Error.OPERATION_INVALID = "OPERATION_INVALID";
        Error.INVALID_AMOUNT_FORMAT = "INVALID_AMOUNT_FORMAT";
        Error.MISSING_MANDATORY_FIELD = "MISSING_MANDATORY_FIELD";
        Error.SUBSCRIPTION_ALREADY_CANCELED = "SUBSCRIPTION_ALREADY_CANCELED";
        Error.RENEWAL_TO_EARLY = "RENEWAL_TO_EARLY";
        Error.TRANSACTION_ALREADY_REJECTED = "TRANSACTION_ALREADY_REJECTED";
        Error.TRANSACTION_ALREADY_COMMITTED = "TRANSACTION_ALREADY_COMMITTED";
        Error.TRANSACTION_NOT_COMMITTED = "TRANSACTION_NOT_COMMITTED";
        Error.CE_NOT_AUTHORIZED = "CE_NOT_AUTHORIZED";
        Error.CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE = "CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE";
        Error.CE_NOT_AUTHORIZED_BARRING_STATE_REACHED = "CE_NOT_AUTHORIZED_BARRING_STATE_REACHED";
        Error.CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING";
        Error.CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO";
        Error.CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED = "CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED";
        Error.CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT = "CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT";
        Error.CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED = "CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED";
        Error.CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED";
        Error.CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED";
        Error.CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT = "CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT";
    })(Error = easypay.Error || (easypay.Error = {}));
})(easypay = exports.easypay || (exports.easypay = {}));
