export module easypay {
    /**
    * Possible Errors (code on message object)
    **/
    export module Error {
        export var OPERATION_INVALID = "OPERATION_INVALID";
        export var INVALID_AMOUNT_FORMAT = "INVALID_AMOUNT_FORMAT";
        export var MISSING_MANDATORY_FIELD = "MISSING_MANDATORY_FIELD";
        export var SUBSCRIPTION_ALREADY_CANCELED = "SUBSCRIPTION_ALREADY_CANCELED";
        export var RENEWAL_TO_EARLY = "RENEWAL_TO_EARLY";
        export var TRANSACTION_ALREADY_REJECTED = "TRANSACTION_ALREADY_REJECTED";
        export var TRANSACTION_ALREADY_COMMITTED = "TRANSACTION_ALREADY_COMMITTED";
        export var TRANSACTION_NOT_COMMITTED = "TRANSACTION_NOT_COMMITTED";
        export var CE_NOT_AUTHORIZED = "CE_NOT_AUTHORIZED";
        export var CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE = "CE_NOT_AUTHORIZED_SIM_NOT_ACTIVE";
        export var CE_NOT_AUTHORIZED_BARRING_STATE_REACHED = "CE_NOT_AUTHORIZED_BARRING_STATE_REACHED";
        export var CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_ROAMING";
        export var CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO = "CE_NOT_AUTHORIZED_NOT_SUPPORTED_TELCO";
        export var CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED = "CE_NOT_AUTHORIZED_BLOCKED_ADULT_CHECK_FAILED";
        export var CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT = "CE_NOT_AUTHORIZED_BLOCKED_CUSTOMER_FOR_ADULT";
        export var CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED = "CE_NOT_AUTHORIZED_BLOCKED_VAS_NOT_ALLOWED";
        export var CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_TOP_STOP_REACHED";
        export var CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED = "CE_NOT_AUTHORIZED_BLOCKED_SPENDING_LIMIT_REACHED";
        export var CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT = "CE_NOT_AUTHORIZED_BLOCKED_NOT_ENOUGH_PREPAID_CREDIT";
    }
}
